/*
 * Academic License - for use in teaching, academic research, and meeting
 * course requirements at degree granting institutions only.  Not for
 * government, commercial, or other organizational use.
 * File: lqr_k.c
 *
 * MATLAB Coder version            : 24.1
 * C/C++ source code generated on  : 20-Jul-2024 15:18:13
 */

/* Include Files */
#include "lqr_k.h"
#include "rt_nonfinite.h"
#include "rt_nonfinite.h"
#include <math.h>

/* Function Declarations */
static double rt_powd_snf(double u0, double u1);

/* Function Definitions */
/*
 * Arguments    : double u0
 *                double u1
 * Return Type  : double
 */
static double rt_powd_snf(double u0, double u1)
{
  double y;
  if (rtIsNaN(u0) || rtIsNaN(u1)) {
    y = rtNaN;
  } else {
    double d;
    double d1;
    d = fabs(u0);
    d1 = fabs(u1);
    if (rtIsInf(u1)) {
      if (d == 1.0) {
        y = 1.0;
      } else if (d > 1.0) {
        if (u1 > 0.0) {
          y = rtInf;
        } else {
          y = 0.0;
        }
      } else if (u1 > 0.0) {
        y = 0.0;
      } else {
        y = rtInf;
      }
    } else if (d1 == 0.0) {
      y = 1.0;
    } else if (d1 == 1.0) {
      if (u1 > 0.0) {
        y = u0;
      } else {
        y = 1.0 / u0;
      }
    } else if (u1 == 2.0) {
      y = u0 * u0;
    } else if ((u1 == 0.5) && (u0 >= 0.0)) {
      y = sqrt(u0);
    } else if ((u0 < 0.0) && (u1 > floor(u1))) {
      y = rtNaN;
    } else {
      y = pow(u0, u1);
    }
  }
  return y;
}

/*
 * LQR_K
 *     K = LQR_K(L0)
 *
 * Arguments    : double L0
 *                double K[12]
 * Return Type  : void
 */
void lqr_k(double L0, double K[12])
{
  double t2;
  double t3;
  /*     This function was generated by the Symbolic Math Toolbox version 24.1.
   */
  /*     27-Jul-2024 17:35:25 */
  t2 = L0 * L0;
  t3 = rt_powd_snf(L0, 3.0);
//  K[0] = ((L0 * -50.738369120908537 + t2 * 168.73288676611921) -
//          t3 * 277.71747427878682) -
//         2.6875305810977892;
//  K[1] = ((L0 * -16.41053558147425 + t2 * 52.304651493814013) -
//          t3 * 62.862564037484013) +
//         2.4077773297174141;
//  K[2] = ((L0 * -3.79285952438204 + t2 * 0.53795935804916) -
//          t3 * 5.39712632191915) -
//         0.34788258861362348;
//  K[3] = ((L0 * -2.3795519725084429 + t2 * 9.0534516314190316) -
//          t3 * 13.093348455609879) +
//         0.33619836382767981;
//  K[4] = ((L0 * -9.1022802166686567 + t2 * 47.138826400659667) -
//          t3 * 83.5018738492099) -
//         2.5346969801909141;
//  K[5] = ((L0 * -21.7241886356339 + t2 * 91.16387942187157) -
//          t3 * 141.7488288180505) +
//         2.2061564840746279;
//  K[6] = ((L0 * -2.423729393950476 + t2 * 6.5481993776432246) -
//          t3 * 12.33887280821885) -
//         2.3946300730855778;
//  K[7] = ((L0 * -20.089807203386481 + t2 * 88.835017296872024) -
//          t3 * 143.792464436029) +
//         1.9279268694789149;
//  K[8] = ((L0 * -68.697916407752459 + t2 * 288.2854993101) -
//          t3 * 448.24915472642982) +
//         6.9764793644248986;
//  K[9] = ((L0 * 28.783937385759788 - t2 * 149.06605765331221) +
//          t3 * 264.05611025542441) +
//         8.0154156357539623;
//  K[10] = ((L0 * -4.4723487119214784 + t2 * 18.486489601473991) -
//           t3 * 28.733067607751678) +
//          0.4913040439106548;
//  K[11] = ((L0 * 1.919723686726168 - t2 * 9.8175959315562586) +
//           t3 * 17.281074817235439) +
//          0.45590187076573768;



  K[0] = ((L0 * -310.8314 + t2 * 189.6798) - t3 * 52.7949) + -0.2098;
  K[1] = ((L0 * 9.1761 - t2 * 2.2110) - t3 * 2.4257) + -0.0013;
  K[2] = ((L0 * -24.4255 + t2 * 12.1061) - t3 * 2.2254) + -0.3391;
  K[3] = ((L0 * -29.3460 + t2 * 14.9541) - t3 * 3.0223) + -0.4706;
  K[4] = ((L0 * -38.9265 + t2 * 25.9886) - t3 * 7.4517) + 1.1938;
  K[5] = ((L0 * -4.4253 + t2 * 3.0516) - t3 * 0.9032) + 0.1643;
  K[6] = ((L0 * 199.2370 - t2 * 85.9481) + t3 * 11.4303) + -0.5810; // a21
  K[7] = ((L0 * 5.9003 - t2 * 3.2110) + t3 * 0.5704) + 0.0352;    // a22
  K[8] = ((L0 * -19.3260 + t2 * 12.4391) - t3 * 3.2696) + 0.4056;  // a23
  K[9] = ((L0 * -26.8162 + t2 * 16.8831) - t3 * 4.3674) + 0.5367;  // a24
  K[10] = ((L0 * 69.1796 - t2 * -35.1428) + t3 * 6.7985) + 0.5314; // a25
  K[11] = ((L0 * 9.2054 - t2 * 4.7264) + t3 * 0.9308) + 0.0671;    // a26


}





/*
 * File trailer for lqr_k.c
 *
 * [EOF]
 */
